### ISSUE TITLE
Nested or multiple filter collections

### ISSUE THREAD

**Issue by Mandolaren** [CoasterKaty/Printers#1]
Hi !
First of all thanks a lot for this script, it's a very nice one to work with :)

I have some issues with nested filter collections, the filter function doesn't seem to work (at least for me ?).

For example, if I have in my xml 

             <Filters>
			<FilterCollection bool="AND" not="0">
			    <FilterOrgUnit bool="AND" not="1" name="a" userContext="0" directMember="0"/>
                        <FilterOrgUnit bool="AND" not="0" name="b" userContext="0" directMember="0"/>
	 			 <FilterCollection bool="AND" not="0">
					<FilterGroup bool="AND" not="0" name="x" userContext="1" directMember="0"/>
					<FilterGroup bool="OR" not="0" name="y" userContext="1" directMember="0"/>
					<FilterGroup bool="OR" not="0" name="z" userContext="1" directMember="0"/>					
				</FilterCollection>
			</FilterCollection>
		</Filters>

Which looks like this in gpp editor 
![Sans titre](https://user-images.githubusercontent.com/3273470/106591254-5bfb9180-654e-11eb-9483-dc9b848a7941.png)

Even if the first collection conditions are not met, printer will be deployed if the second collection conditions are met.

If I change the rules to be like this :

                     <Filters>	
				<FilterCollection bool="AND" not="0">		
				    <FilterOrgUnit bool="AND" not="1" name="an" userContext="0" directMember="0"/>
				    <FilterOrgUnit bool="AND" not="0" name="b" userContext="0" directMember="0" />
				</FilterCollection>
				<FilterCollection bool="AND" not="0">
					<FilterGroup bool="AND" not="0" name="x" userContext="1" directMember="0"/>
					<FilterGroup bool="OR" not="0" name="y" userContext="1" directMember="0"/>
					<FilterGroup bool="OR" not="0" name="as" userContext="1" directMember="0"/>
				</FilterCollection>	
		    </Filters> 
Which looks like this in gpp editor 
![Sans titre1](https://user-images.githubusercontent.com/3273470/106594027-d4b01d00-6551-11eb-8358-f42e82203a21.png)

Even if the second collection conditions are not met, printer will be deployed (because the first collection conditions are met).

Thanks !

**Comment by CoasterKaty** [comment]
That's odd, I tested it with quite a few different variations but obviously not two collections like that. Will have a look at it when I get chance.

**Comment by CoasterKaty** [comment]
Line 85, return  evaluateFilters $Filter
Should read:
$return = evaluateFilters $Filter

then it seems to work, at least it did when I tested it with your first XML, the second one in the screenshot the "user in group" bits are following an empty collection, rather than being inside the collection.

**Comment by Mandolaren** [comment]
Hi  !
Thanks a lot for your time ! It works as intended :)
I'll soon won't be able to create my own gpp, so I'm using your script to
process all my existing gpp files (shortcuts, printers, files, whatever)
with a fine item level targeting.
Best regards,

Le mar. 2 févr. 2021 à 18:17, CoasterKaty <notifications@github.com> a
écrit :
